package faker

import (
	"errors"
	"reflect"

	"github.com/davecgh/go-spew/spew"

	"github.com/brianvoe/gofakeit"
)

var funcs = map[string]interface{}{
	"Address":              gofakeit.Address,
	"BeerAlcohol":          gofakeit.BeerAlcohol,
	"BeerBlg":              gofakeit.BeerBlg,
	"BeerHop":              gofakeit.BeerHop,
	"BeerIbu":              gofakeit.BeerIbu,
	"BeerMalt":             gofakeit.BeerMalt,
	"BeerName":             gofakeit.BeerName,
	"BeerStyle":            gofakeit.BeerStyle,
	"BeerYeast":            gofakeit.BeerYeast,
	"Bool":                 gofakeit.Bool,
	"BS":                   gofakeit.BS,
	"BuzzWord":             gofakeit.BuzzWord,
	"Categories":           gofakeit.Categories,
	"ChromeUserAgent":      gofakeit.ChromeUserAgent,
	"City":                 gofakeit.City,
	"Color":                gofakeit.Color,
	"Company":              gofakeit.Company,
	"CompanySuffix":        gofakeit.CompanySuffix,
	"Contact":              gofakeit.Contact,
	"Country":              gofakeit.Country,
	"CountryAbr":           gofakeit.CountryAbr,
	"CreditCard":           gofakeit.CreditCard,
	"CreditCardCvv":        gofakeit.CreditCardCvv,
	"CreditCardExp":        gofakeit.CreditCardExp,
	"CreditCardNumber":     gofakeit.CreditCardNumber,
	"CreditCardNumberLuhn": gofakeit.CreditCardNumberLuhn,
	"CreditCardType":       gofakeit.CreditCardType,
	"Currency":             gofakeit.Currency,
	"CurrencyLong":         gofakeit.CurrencyLong,
	"CurrencyShort":        gofakeit.CurrencyShort,
	"Date":                 gofakeit.Date,
	"DateRange":            gofakeit.DateRange,
	"Day":                  gofakeit.Day,
	"DomainName":           gofakeit.DomainName,
	"DomainSuffix":         gofakeit.DomainSuffix,
	"Email":                gofakeit.Email,
	"Extension":            gofakeit.Extension,
	"FirefoxUserAgent":     gofakeit.FirefoxUserAgent,
	"FirstName":            gofakeit.FirstName,
	"Float32":              gofakeit.Float32,
	"Float32Range":         gofakeit.Float32Range,
	"Float64":              gofakeit.Float64,
	"Float64Range":         gofakeit.Float64Range,
	"Gender":               gofakeit.Gender,
	"Generate":             gofakeit.Generate,
	"HackerAbbreviation":   gofakeit.HackerAbbreviation,
	"HackerAdjective":      gofakeit.HackerAdjective,
	"HackerIngverb":        gofakeit.HackerIngverb,
	"HackerNoun":           gofakeit.HackerNoun,
	"HackerPhrase":         gofakeit.HackerPhrase,
	"HackerVerb":           gofakeit.HackerVerb,
	"HexColor":             gofakeit.HexColor,
	"HipsterParagraph":     gofakeit.HipsterParagraph,
	"HipsterSentence":      gofakeit.HipsterSentence,
	"HipsterWord":          gofakeit.HipsterWord,
	"Hour":                 gofakeit.Hour,
	"HTTPMethod":           gofakeit.HTTPMethod,
	"ImageURL":             gofakeit.ImageURL,
	"Int16":                gofakeit.Int16,
	"Int32":                gofakeit.Int32,
	"Int64":                gofakeit.Int64,
	"Int8":                 gofakeit.Int8,
	"IPv4Address":          gofakeit.IPv4Address,
	"IPv6Address":          gofakeit.IPv6Address,
	"Job":                  gofakeit.Job,
	"JobDescriptor":        gofakeit.JobDescriptor,
	"JobLevel":             gofakeit.JobLevel,
	"JobTitle":             gofakeit.JobTitle,
	"LastName":             gofakeit.LastName,
	"Latitude":             gofakeit.Latitude,
	"LatitudeInRange":      gofakeit.LatitudeInRange,
	"Letter":               gofakeit.Letter,
	"Lexify":               gofakeit.Lexify,
	"LogLevel":             gofakeit.LogLevel,
	"Longitude":            gofakeit.Longitude,
	"LongitudeInRange":     gofakeit.LongitudeInRange,
	"MimeType":             gofakeit.MimeType,
	"Minute":               gofakeit.Minute,
	"Month":                gofakeit.Month,
	"Name":                 gofakeit.Name,
	"NamePrefix":           gofakeit.NamePrefix,
	"NameSuffix":           gofakeit.NameSuffix,
	"NanoSecond":           gofakeit.NanoSecond,
	"Number":               gofakeit.Number,
	"Numerify":             gofakeit.Numerify,
	"OperaUserAgent":       gofakeit.OperaUserAgent,
	"Paragraph":            gofakeit.Paragraph,
	"Password":             gofakeit.Password,
	"Person":               gofakeit.Person,
	"Phone":                gofakeit.Phone,
	"PhoneFormatted":       gofakeit.PhoneFormatted,
	"Price":                gofakeit.Price,
	"RandString":           gofakeit.RandString,
	"RGBColor":             gofakeit.RGBColor,
	"SafariUserAgent":      gofakeit.SafariUserAgent,
	"SafeColor":            gofakeit.SafeColor,
	"Second":               gofakeit.Second,
	"Seed":                 gofakeit.Seed,
	"Sentence":             gofakeit.Sentence,
	"ShuffleInts":          gofakeit.ShuffleInts,
	"ShuffleStrings":       gofakeit.ShuffleStrings,
	"SimpleStatusCode":     gofakeit.SimpleStatusCode,
	"SSN":                  gofakeit.SSN,
	"State":                gofakeit.State,
	"StateAbr":             gofakeit.StateAbr,
	"StatusCode":           gofakeit.StatusCode,
	"Street":               gofakeit.Street,
	"StreetName":           gofakeit.StreetName,
	"StreetNumber":         gofakeit.StreetNumber,
	"StreetPrefix":         gofakeit.StreetPrefix,
	"StreetSuffix":         gofakeit.StreetSuffix,
	"Struct":               gofakeit.Struct,
	"TimeZone":             gofakeit.TimeZone,
	"TimeZoneAbv":          gofakeit.TimeZoneAbv,
	"TimeZoneFull":         gofakeit.TimeZoneFull,
	"TimeZoneOffset":       gofakeit.TimeZoneOffset,
	"Uint16":               gofakeit.Uint16,
	"Uint32":               gofakeit.Uint32,
	"Uint64":               gofakeit.Uint64,
	"Uint8":                gofakeit.Uint8,
	"URL":                  gofakeit.URL,
	"UserAgent":            gofakeit.UserAgent,
	"Username":             gofakeit.Username,
	"UUID":                 gofakeit.UUID,
	"WeekDay":              gofakeit.WeekDay,
	"Word":                 gofakeit.Word,
	"Year":                 gofakeit.Year,
	"Zip":                  gofakeit.Zip,
}

func Call(m map[string]interface{}, name string, params ...interface{}) (result []reflect.Value, err error) {
	f := reflect.ValueOf(m[name])
	spew.Dump(params)
	if len(params) != f.Type().NumIn() {
		err = errors.New("the number of params is not adapted.")
		return
	}
	in := make([]reflect.Value, len(params))
	for k, param := range params {
		in[k] = reflect.ValueOf(param)
	}
	result = f.Call(in)
	return
}
